openapi: 3.1.0
info:
  title: HR App
  version: "0.1.0"
servers:
  - url: http://127.0.0.1:81
    description: Docker

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/login:
    $ref: "./paths/auth/login.yaml#/login"
  /api/roles:
    $ref: "./paths/module/company/role/roles.yaml#/roles"
  /api/roles/{uuid}:
    $ref: "./paths/module/company/role/roles_uuid.yaml#/roles"
  /api/roles/multiple:
    $ref: "./paths/module/company/role/roles_multiple.yaml#/roles"
  /api/roles/import:
    $ref: "./paths/module/company/role/roles_import.yaml#/roles"
  /api/roles/{uuid}/accesses:
    $ref: "./paths/module/company/role/roles_accesses.yaml#/roles"
  /api/roles/{uuid}/acesses/permissions:
    $ref: "./paths/module/company/role/roles_permissions.yaml#/roles"
  /api/notes:
    $ref: "./paths/module/note/notes.yaml#/notes"
  /api/notes/{uuid}:
    $ref: "./paths/module/note/notes_uuid.yaml#/notes"