openapi: 3.1.0
info:
  title: HR App
  version: "0.1.0"
servers:
  - url: http://127.0.0.1:81
    description: Docker

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/login:
    post:
      summary: Logowanie
      description: Umożliwia autentykację.
      tags:
        - Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas/module/auth/login.yaml#/loginPayload"
      responses:
        200:
          $ref: "./components/responses/auths/login.yaml#/LoginSuccess"
        401:
          $ref: "./components/responses/auths/login.yaml#/LoginFailed"
  /api/roles:
    post:
      summary: "Dodaje rolę"
      description: "Pozwala na dodanie roli"
      tags:
        - Roles
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas/module/company/roles/create.yaml#/createRole"
      responses:
        "201":
          $ref: "./components/responses/module/company/roles/create.yaml#/createSuccess"
        "422":
          $ref: "./components/responses/module/company/roles/create.yaml#/nameError"
        "500":
          $ref: "./components/responses/module/company/roles/create.yaml#/createError"
    get:
      summary: "Pobiera listę ról"
      description: "Pozwala na pobranie listy ról"
      tags:
        - Roles
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          description: "Numer strony (paginacja)"
          required: false
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          description: "Liczba elementów na stronę"
          required: false
          schema:
            type: integer
            default: 10
        - name: sortBy
          in: query
          description: "Pole do sortowania (np. name)"
          required: false
          schema:
            type: string
            example: "name"
        - name: sortDirection
          in: query
          description: "Kierunek sortowania"
          required: false
          schema:
            type: string
            enum: [ asc, desc ]
            example: "desc"
        - name: deleted
          in: query
          description: "Filtr usuniętych rekordów (0 - aktywne, 1 - usunięte)"
          required: false
          schema:
            type: integer
            enum: [ 0, 1 ]
            example: 0
        - name: phrase
          in: query
          description: "Wyszukiwana fraza"
          required: false
          schema:
            type: string
            example: "user"
        - name: includes
          in: query
          description: "Relacje do załadowania (np. employees)"
          required: false
          schema:
            type: string
            example: "employees"
      responses:
        '200':
          $ref: "./components/responses/module/company/roles/list.yaml#/listSuccess"
  /api/roles/{uuid}:
    get:
      summary: "Pobiera wskazaną rolę"
      description: "Pozwala na pobranie wskazanej roli"
      tags:
        - Roles
      security:
        - BearerAuth: [ ]
      parameters:
        - name: uuid
          in: path
          required: true
          description: "UUID roli"
          schema:
            type: string
            format: uuid
            example: "45df2733-666f-42dc-90d2-a76a177bab1d"
      responses:
        "200":
          $ref: "./components/responses/module/company/roles/get.yaml#/getSuccess"
        "404":
          $ref: "./components/responses/module/company/roles/get.yaml#/notFoundRole"
        "500":
          $ref: "./components/responses/module/company/roles/get.yaml#/getError"
    put:
      summary: "Aktualizuje wskazaną rolę"
      description: "Pozwala na aktualizację wskazanej roli"
      tags:
        - Roles
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas/module/company/roles/update.yaml#/updateRole"
      responses:
        "201":
          $ref: "./components/responses/module/company/roles/update.yaml#/updateSuccess"
        "422":
          $ref: "./components/responses/module/company/roles/update.yaml#/nameError"
        "500":
          $ref: "./components/responses/module/company/roles/update.yaml#/updateError"
    delete:
      summary: "Usuwa wskazana rolę"
      description: "Pozwala na usunięcie wskazanej roli"
      tags:
        - Roles
      security:
        - BearerAuth: []
      parameters:
        - name: uuid
          in: path
          required: true
          description: "UUID roli"
          schema:
            type: string
            format: uuid
            example: "45df2733-666f-42dc-90d2-a76a177bab1d"
      responses:
        "200":
          $ref: "./components/responses/module/company/roles/delete.yaml#/deleteSuccess"
        "404":
          $ref: "./components/responses/module/company/roles/delete.yaml#/notFoundRole"
        "500":
          $ref: "./components/responses/module/company/roles/delete.yaml#/deleteError"
  /api/roles/multiple:
    delete:
      summary: "Usuwa wskazane role"
      description: "Pozwala na usunięcie wskazanych ról"
      tags:
        - Roles
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                selectedUUID:
                  type: array
                  description: "Lista UUID ról do usunięcia"
                  items:
                    type: string
                    format: uuid
                  example:
                    - "35b3c753-63e9-4a2f-96f3-30b63dbc927a"
                    - "815c4384-0c71-4a43-9c14-fa3ceb7a4f40"
                    - "b7a52f19-40b2-447a-bf0e-079c5405cbf2"
              required:
                - selectedUUID
      responses:
        "200":
          $ref: "./components/responses/module/company/roles/delete_multiple.yaml#/deleteSuccess"
        "422":
          $ref: "./components/responses/module/company/roles/delete_multiple.yaml#/notFoundRole"
        "500":
          $ref: "./components/responses/module/company/roles/delete_multiple.yaml#/deleteError"
  /api/roles/import:
    post:
      summary: "Importuje role z pliku"
      description: "Pozwala na import ról z pliku Excel (.xlsx). Wymagana kolumna 'name' (min 3, max 50 znaków). Opcjonalnie 'description'."
      tags:
        - Roles
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "./components/schemas/module/company/roles/import.yaml#/importRoles"
      responses:
        "201":
          $ref: "./components/responses/module/company/roles/import.yaml#/importSuccess"
        "500":
          $ref: "./components/responses/module/company/roles/import.yaml#/importError"
  /api/roles/{uuid}/accesses:
    post:
      summary: "Dodaje dostępy dla roli"
      description: "Pozwala dodać wybrane dostepy dla danej roli"
      tags:
        - Roles
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas/module/company/roles/access.yaml#/createRoleAccesses"
      responses:
        "201":
          $ref: "./components/responses/module/company/roles/access.yaml#/createAccessSuccess"
        "500":
          $ref: "./components/responses/module/company/roles/access.yaml#/createAccessError"
  /api/roles/{uuid}/accesses/permissions:
    post:
      summary: "Dodaje pozwolenia dostępu dla roli"
      description: "Pozwala dodać wybrane pozwolenia dostepu dla danej roli"
      tags:
        - Roles
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas/module/company/roles/permission.yaml#/createRoleAccessesPermissions"
      responses:
        "201":
          $ref: "./components/responses/module/company/roles/permission.yaml#/createPermissionSuccess"
        "500":
          $ref: "./components/responses/module/company/roles/permission.yaml#/createPermissionError"
  /api/notes:
    post:
      summary: "Dodaje notatkę"
      description: "Pozwala na dodanie notatki"
      tags:
        - Notes
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/schemas/module/note/create.yaml#/createRole"
      responses:
        "201":
          $ref: "./components/responses/module/note/create.yaml#/createSuccess"
        "422":
          $ref: "./components/responses/module/note/create.yaml#/nameError"
        "500":
          $ref: "./components/responses/module/note/create.yaml#/createError"