openapi: 3.1.0
info:
  title: HR App
  version: "0.1.0"
servers:
  - url: http://127.0.0.1:81
    description: Docker

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/login:
    $ref: "./paths/auths/login.yaml#/login"
  /api/roles:
    $ref: "./paths/module/company/roles/create.yaml#/createRole"
