deleteSuccess:
  description: "Rola została usunięta"
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
            example: "Rola została pomyślnie usunięta"
notFoundRole:
  description: "Nie znaleziono roli o podanym UUID"
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
            example: "Wystapił błąd przy pobieraniu wybranej roli: Rola o podanym UUID nie istnieje : 45df2733-666f-42dc-90d2-a76a177bab1e"
        required:
          - message
deleteError:
  description: "Rola nie została usunięta"
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
            example: "Wystąpił błąd - rola nie została usunięta"