updateSuccess:
  description: "Rola została zaktualizowana"
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
            example: "Rola została pomyślnie zaktualizowana"
updateError:
  description: "Rola nie została zaktualizowana"
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
            example: "Wystąpił błąd - rola nie została zaktualizowana"
nameError:
  description: "Rola nie została zaktualizowana"
  content:
    application/json:
      schema:
        type: object
        properties:
          errors:
            type: object
            additionalProperties:
              type: string
            example:
              nazwa: "Minimalnie znaków 3"