api_company_delete:
  path: api/companies/{uuid}
  controller: App\Module\Company\Presentation\API\Controller\Company\DeleteCompanyController::delete
  methods: [DELETE]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'

api_company_get:
  path: api/companies/{uuid}
  controller: App\Module\Company\Presentation\API\Controller\Company\GetCompanyController::get
  methods: [GET]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'

api_company_create:
  path: api/companies
  controller: App\Module\Company\Presentation\API\Controller\Company\CreateCompanyController::create
  methods: [POST]

api_company_import:
  path: api/companies/import
  controller: App\Module\Company\Presentation\API\Controller\Company\ImportCompaniesController::import
  methods: [POST]

api_company_delete_multiple:
  path: api/companies/multiple
  controller: App\Module\Company\Presentation\API\Controller\Company\DeleteMultipleCompaniesController::delete
  methods: [DELETE]

api_company_update:
  path: api/companies/{uuid}
  controller: App\Module\Company\Presentation\API\Controller\Company\UpdateCompanyController::update
  methods: [ PUT ]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'

api_companies_list:
  path: api/companies
  controller: App\Module\Company\Presentation\API\Controller\Company\ListCompaniesController::list
  methods: [GET]

api_company_restore:
  path: api/companies/{uuid}/restore
  controller: App\Module\Company\Presentation\API\Controller\Company\RestoreCompanyController::restore
  methods: [ PATCH ]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'