api_company_create:
  path: api/companies
  controller: App\Module\Company\Presentation\API\Controller\Company\CreateCompanyController::create
  methods: [POST]

api_company_import:
  path: api/companies/import
  controller: App\Module\Company\Presentation\API\Controller\Company\ImportCompaniesController::import
  methods: [POST]

api_company_update:
  path: api/companies/{uuid}
  controller: App\Module\Company\Presentation\API\Controller\Company\UpdateCompanyController::update
  methods: [ PUT ]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'