api_department_delete:
  path: api/departments/{uuid}
  controller: App\Module\Company\Presentation\API\Controller\Department\DeleteDepartmentController::delete
  methods: [DELETE]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'
    
api_department_get:
  path: api/departments/{uuid}
  controller: App\Module\Company\Presentation\API\Controller\Department\GetDepartmentController::get
  methods: [GET]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'    

api_department_create:
  path: api/departments
  controller: App\Module\Company\Presentation\API\Controller\Department\CreateDepartmentController::create
  methods: [POST]

api_department_update:
  path: api/departments/{uuid}
  controller: App\Module\Company\Presentation\API\Controller\Department\UpdateDepartmentController::update
  methods: [ PUT ]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'
    
api_department_delete_multiple:
  path: api/departments/multiple
  controller: App\Module\Company\Presentation\API\Controller\Department\DeleteMultipleDepartmentsController::delete
  methods: [DELETE]    