api_employee_create:
  path: api/employees
  controller: App\Module\Company\Presentation\API\Controller\Employee\CreateEmployeeController::create
  methods: [POST]

api_employee_update:
  path: api/employees/{uuid}
  controller: App\Module\Company\Presentation\API\Controller\Employee\UpdateEmployeeController::update
  methods: [ PUT ]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'