api_role_delete:
  path: api/roles/{uuid}
  controller: App\Module\Company\Presentation\API\Controller\Role\DeleteRoleController::delete
  methods: [DELETE]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'

api_role_get:
  path: api/roles/{uuid}
  controller: App\Module\Company\Presentation\API\Controller\Role\GetRoleController::get
  methods: [GET]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'

api_role_update:
  path: api/roles/{uuid}
  controller: App\Module\Company\Presentation\API\Controller\Role\UpdateRoleController::update
  methods: [PUT]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'

api_role_access_permission_create:
  path: api/roles/{uuid}/accesses/permissions
  controller: App\Module\Company\Presentation\API\Controller\Role\CreateRoleAccessPermissionController::create
  methods: [POST]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'

api_role_access_create:
  path: api/roles/{uuid}/accesses
  controller: App\Module\Company\Presentation\API\Controller\Role\CreateRoleAccessController::create
  methods: [POST]
  requirements:
    uuid: '[0-9a-fA-F-]{36}'

api_role_delete_multiple:
  path: api/roles/multiple
  controller: App\Module\Company\Presentation\API\Controller\Role\DeleteMultipleRolesController::delete
  methods: [DELETE]

api_role_create:
  path: api/roles
  controller: App\Module\Company\Presentation\API\Controller\Role\CreateRoleController::create
  methods: [POST]

api_roles_import:
  path: api/roles/import
  controller: App\Module\Company\Presentation\API\Controller\Role\ImportRolesController::import
  methods: [POST]

api_roles_list:
  path: api/roles
  controller: App\Module\Company\Presentation\API\Controller\Role\ListRolesController::list
  methods: [GET]