nelmio_api_doc:
  areas:
    default:
      path_patterns: [ ^/api ]
    notes:
      path_patterns: [ ^/api/notes ]
    roles:
      path_patterns: [ ^/api/roles ]
  documentation:
    servers:
      - url: "http://127.0.0.1:81/"
        description: API over HTTP
    info:
      title: HRApp
      description: This is an awesome app!
      version: 1.0.0
      x-build:
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []
    paths:
      /api/notes:
        get:
          tags:
            - notes
          summary: Get all notes
          description: Returns a list of all notes.
          responses:
            '200':
              description: A list of notes
        post:
          tags:
            - notes
          summary: Create a new note
          description: Creates a new note.
          requestBody:
            required: true
          responses:
            '201':
              description: Role created