nelmio_api_doc:
  documentation:
    servers:
      - url: "http://127.0.0.1:81/"
        description: API over HTTP
    info:
      title: HRApp
      description: This is an awesome app!
      version: 1.0.0
      x-build:
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []
    paths:
      /api/roles:
        get:
          tags:
            - roles
          summary: Get all roles
          description: Returns a list of all roles.
          responses:
            '200':
              description: A list of roles
        post:
          tags:
            - roles
          summary: Create a new role
          description: Creates a new role.
          requestBody:
            required: true
          responses:
            '201':
              description: Role created