framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction
            query.bus:
                middleware:
                    - validation

        transports:
#            https://symfony.com/doc/current/messenger.html#transport-configuration
#            async: '%env(MESSENGER_TRANSPORT_DSN)%'
#            failed: 'doctrine://default?queue_name=failed'
#            sync: 'sync://'

            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            company_xlsx_import:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/company_xlsx_import'
                options:
                    exchange:
                        name: 'company_xlsx_import' # Nazwa exchange (wymiana)
                        type: direct # Typ exchange (direct, fanout, topic itp.)
        routing:
            #'App\Module\Company\Application\Command\Company\ImportCompaniesCommand': async
            'App\Module\Company\Application\Command\Company\ImportCompaniesCommand': company_xlsx_import

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
