framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction
            query.bus:
                middleware:
                    - validation
                default_middleware: allow_no_handlers
            event.bus: ~
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            company_xlsx_import:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/company_xlsx_import'
                options:
                    exchange:
                        name: 'company_xlsx_import' # Nazwa exchange (wymiana)
                        type: direct # Typ exchange (direct, fanout, topic itp.)
            department_xlsx_import:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/department_xlsx_import'
                options:
                    exchange:
                        name: 'department_xlsx_import'
                        type: direct
            employee_xlsx_import:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/employee_xlsx_import'
                options:
                    exchange:
                        name: 'employee_xlsx_import'
                        type: direct
        routing:
            #'App\Module\Company\Application\Command\Company\ImportCompaniesCommand': async
            #'App\Module\Company\Application\Command\Company\ImportCompaniesCommand': company_xlsx_import
            #'App\Module\Company\Application\Command\Department\ImportDepartmentsCommand': department_xlsx_import
            #'App\Module\Company\Application\Command\Employee\ImportEmployeesCommand': employee_xlsx_import

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
