nelmio_api_doc:
  documentation:
    servers:
      - url: "http://127.0.0.1:81/"
        description: API over HTTP
    info:
      title: HRApp
      description: This is an awesome app!
      version: 1.0.0
      x-build:
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []
  areas:
    default:
      path_patterns: [ ^/api ]
    roles:
      path_patterns: [ ^/api/roles ]
    notes:
      path_patterns: [ ^/api/notes ]