imports:
    - { resource: './services/main.yaml' }
    - { resource: './services/module/company/role.yaml' }
    - { resource: './services/module/company/position.yaml' }
    - { resource: './services/module/company/contract_type.yaml' }
    - { resource: './services/module/note/note.yaml' }
