# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Module\Company\Domain\Entity\User:
        arguments:
            $userPasswordHasher: '@security.user_password_hasher'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    #Role handlers
    App\Module\Company\Application\CommandHandler\Role\CreateRoleCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\Module\Company\Application\CommandHandler\Role\UpdateRoleCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\Module\Company\Application\CommandHandler\Role\DeleteRoleCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\Module\Company\Application\CommandHandler\Role\ImportRolesCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    #Note handlers
    App\Module\Note\Application\CommandHandler\CreateNoteCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\Module\Note\Application\CommandHandler\UpdateNoteCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\Module\Note\Application\CommandHandler\DeleteNoteCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
