api_notice_get:
  path: api/notes/{uuid}
  controller: App\Module\Note\Presentation\API\GetNoteController::get
  methods: [ GET ]
api_note_create:
  path: api/notes
  controller: App\Module\Note\Presentation\API\CreateNoteController::create
  methods: [POST]
api_note_update:
  path: api/notes/{uuid}
  controller: App\Module\Note\Presentation\API\UpdateNoteController::update
  methods: [PUT]
api_note_delete:
  path: api/notes/{uuid}
  controller: App\Module\Note\Presentation\API\DeleteNoteController::delete
  methods: [DELETE]