services:
    _defaults:
        autowire: true
        autoconfigure: true
    #Industry handlers
    App\Module\Company\Application\CommandHandler\Industry\CreateIndustryCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\Module\Company\Application\CommandHandler\Industry\UpdateIndustryCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
#    App\Module\Company\Application\CommandHandler\Industry\DeleteIndustryCommandHandler:
#        tags:
#            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
#    App\Module\Company\Application\CommandHandler\Industry\DeleteMultipleIndustriesCommandHandler:
#        tags:
#            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
#    App\Module\Company\Application\CommandHandler\Industry\ImportIndustriesCommandHandler:
#        tags:
#            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }