services:
    _defaults:
        autowire: true
        autoconfigure: true
    #Position handlers
    App\Module\Company\Application\CommandHandler\Position\CreatePositionCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
#    App\Module\Company\Application\CommandHandler\Position\UpdatePositionCommandHandler:
#        tags:
#            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
#    App\Module\Company\Application\CommandHandler\Position\DeletePositionCommandHandler:
#        tags:
#            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
#    App\Module\Company\Application\CommandHandler\Position\DeleteMultiplePositionsCommandHandler:
#        tags:
#            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
#    App\Module\Company\Application\CommandHandler\Position\ImportPositionsCommandHandler:
#        tags:
#            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }