services:
    _defaults:
        autowire: true
        autoconfigure: true
    #Role handlers
    App\Module\Company\Application\CommandHandler\Role\CreateRoleCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\Module\Company\Application\CommandHandler\Role\UpdateRoleCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\Module\Company\Application\CommandHandler\Role\DeleteRoleCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
    App\Module\Company\Application\CommandHandler\Role\ImportRolesCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }