name: Symfony CI

on:
  push:
    branches:
      - "master"
      - "feature/**"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      APP_ENV: test
      DATABASE_URL: "mysql://root:root_password@service-company-db:3306/service_company_test?charset=utf8mb4"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show current dir
        run: pwd

      - name: List files
        run: ls -la ../../

      - name: Set up Docker
        working-directory: ${{ github.workspace }}
        run: docker compose up -d --build

      - name: Wait for MySQL to be healthy
        working-directory: ${{ github.workspace }}
        run: |
          docker compose exec -T service-company-db-test \
            bash -c 'until mysqladmin ping -h localhost --silent; do sleep 1; done'

      - name: Install Composer dependencies
        run: |
          docker compose exec -T service-company composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Doctrine migrations
        run: |
          docker compose exec -T service-company php bin/console doctrine:migrations:migrate --no-interaction

      - name: Initialize system data
        run: |
          docker compose exec -T service-company php bin/console app:initialize-system-default-data
          docker compose exec -T service-company php bin/console app:initialize-system-fake-data

      - name: Run PHPUnit tests
        run: |
          docker compose exec -T service-company php bin/phpunit

